### ISSUE TITLE
缺失了一个文件？

### ISSUE THREAD

**Issue by Zyh716** [thunlp/VisualDS#1]
您好，您发布的代码非常方便使用，并且运行结果很棒。非常感谢您的开源！我在一步一步运行脚本命令的时候，没有找到cmds/20/motif/predcls/ds/em_M_step2_wclip.sh这个文件，请问您方便提供一下这个文件吗？万分感谢！！

**Comment by waxnkw** [comment]
感谢您的提醒！确实少了一个文件。我已经添加了，您可以在[这里](https://github.com/thunlp/VisualDS/blob/main/cmds/20/motif/predcls/ds/em_M_step2_wclip.sh)查看。

**Comment by Zyh716** [comment]
已经可以看到文件了！感谢您的及时处理，再次感谢您优秀的开源工作！
