### ISSUE TITLE
how to convert the KB to json file?

### ISSUE THREAD

**Issue by ZHUXUHAN** [thunlp/VisualDS#10]
I just try to map the KB triplet to the VG data from your provied KB json file, but i find it is hard to align, can you tell me how did you align them? Are there any special skills?
Looking for forward you replaying.

**Comment by waxnkw** [comment]
I use the code `from lemminflect import getLemma` and  `getLemma(x, upos='VERB')` to lemmatize the verbs in the predicates. After that simple string comparison is conducted to align.

**Comment by ZHUXUHAN** [comment]
> I use the code `from lemminflect import getLemma` and `getLemma(x, upos='VERB')` to lemmatize the verbs in the predicates. After that simple string comparison is conducted to align.

thank you very much for your answering, but how do you align the subjects and objects to VG-150 categories?
and there are only 30% wrong triplets compared with the GT (few noise) in your provided generated labels,  but when i try to align the triplets, there are much noise, how did do to achieve that?

can you provide with the related codes?

**Comment by waxnkw** [comment]
Sorry, I lost my code for aligning subjects and objects. I think I just conduct string comparison or first lemmatize and then compare the string. The intermediate result with aligned subjects and objects is [here](https://thunlp.oss-cn-qingdao.aliyuncs.com/CC_150objs_4000rels.json).
The code of aligning relations is [here](https://thunlp.oss-cn-qingdao.aliyuncs.com/visds/construct_kb.ipynb).

**Comment by ZHUXUHAN** [comment]
> Sorry, I lost my code for aligning subjects and objects. I think I just conduct string comparison or first lemmatize and then compare the string. The intermediate result with aligned subjects and objects is [here](https://thunlp.oss-cn-qingdao.aliyuncs.com/CC_150objs_4000rels.json). The code of aligning relations is [here](https://thunlp.oss-cn-qingdao.aliyuncs.com/visds/construct_kb.ipynb).

thank you very much, i understand it.
