### ISSUE TITLE
关于数据集的文件问题

### ISSUE THREAD

**Issue by zhuzq-iziy** [thunlp/VisualDS#5]
您好，您的工作很好，对我的启发很大！
请问是否方便提供处理50类predicates相关的数据文件呢？例如: VGKB.json, CCKB.json, cc_clip_logits.pk, vg_clip_logits.pk等。
以方便复现您在附录中展示的50类的性能以及迁移至其他50类的模型中。
万分感谢！

**Comment by waxnkw** [comment]
感谢使用！ 最近比较忙。我会在周日之前回复您。

**Comment by waxnkw** [comment]
https://drive.google.com/file/d/1U2IesUJvexO7QFrmMulmDbN87bZ_8NK-/view?usp=sharing
这是50类相关文件。

**Comment by zhuzq-iziy** [comment]
感谢您的回复和分享！对我的帮助很大，谢谢！
