### ISSUE TITLE
about raw KB data?

### ISSUE THREAD

**Issue by ZHUXUHAN** [thunlp/VisualDS#6]
hi, how the raw KB data get?

**Comment by waxnkw** [comment]
The raw KB data is automatically parsed from captions in the Conceptual Caption dataset. For example, from "the cat eats the fruit", we can get "(cat, eat, fruit)". You can download the raw KB from https://thunlp.oss-cn-qingdao.aliyuncs.com/CC_allobjs_4000rels.json.

**Comment by ZHUXUHAN** [comment]
> 

hi, can you share the code to extract the KB?

**Comment by waxnkw** [comment]
This is the link to the tool: https://nlp.stanford.edu/software/scenegraph-parser.shtml.

**Comment by ZHUXUHAN** [comment]
> This is the link to the tool: https://nlp.stanford.edu/software/scenegraph-parser.shtml.

ok, thank you very much.
